### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by A-Pot**
Good afternoon. If I may, I would like to incorporate a prototype Shiny App that was demoed last week as part of the development of the OHDSI Gold Standard Phenotype Library. Details about this effort can be found [here](http://forums.ohdsi.org/t/requirements-development-for-the-ohdsi-gold-standard-phenotype-library/4876), but the gist of it is that this app would function as a viewer into OHDSI's phenotype library - the entries of which would be housed elsewhere in a separate GitHub repository.

The app is very much under development (and warns on every page that this is so). However, having it hosted here would be extremely helpful in making it more accessible to the community so that others can explore it and provide feedback to help guide it into its final form. Thanks for your consideration!

### CODE REVIEW

**Comment by A-Pot** [comment]
@schuemie , thank you for merging. I have just one more follow-up item. Currently, when I [go to the app](http://data.ohdsi.org/PhenotypeLibraryViewer/), I'm greeted with `ERROR: there is no package called ‘shinyWidgets’`. Is it possible for the `shinyWidgets` package to be installed on the backend so it becomes recognized?

**Comment by leeevans** [comment]
@A-Pot I did a temporary install of the shinyWidgets package so your app can use it now. I'll add that package to the shiny server build later so its permanently installed.

**Comment by A-Pot** [comment]
Thank you, @leeevans , that's perfect!

**Comment by A-Pot** [comment]
Also @schuemie and/or @leeevans, could I please get write (push) permissions to this repo for the sole purpose of modifying the `PhenotypeLibraryViewer` app? It appears there are some fixes that will need to take place in order for the app to function correctly, with plenty of development sure to come in the future.

**Comment by A-Pot** [comment]
> Also @schuemie and/or @leeevans, could I please get write (push) permissions to this repo for the sole purpose of modifying the `PhenotypeLibraryViewer` app? It appears there are some fixes that will need to take place in order for the app to function correctly, with plenty of development sure to come in the future.

@schuemie, @leeevans , (or other principal contributors?) is there a process I can go through to get push permissions for this repo for the purpose of developing the `PhenotypeLibraryViewer` app?

**Pull request merged**
